version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - mysqldb
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysqldb;Port=3306;Database=VehicleContext;User=root;Password=black;

  mysqldb:
    image: linuxserver/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: black
      MYSQL_DATABASE: VehicleContext
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
